services:
  node1:
    build: ./node
    networks:
      - isotope-net
    ports:
      - "9001:9000"
      - "8081:8081"
    volumes:
      - ./state:/root/state
    environment:
      - NODE_ID=1
      - ISOTOPE_ETHICS_HASH=${ISOTOPE_ETHICS_HASH}

  node2:
    build: ./node
    networks:
      - isotope-net
    ports:
      - "9002:9000"
      - "8082:8081"
    volumes:
      - ./state:/root/state
    environment:
      - NODE_ID=2
      - ISOTOPE_ETHICS_HASH=${ISOTOPE_ETHICS_HASH}

  node3:
    build: ./node
    networks:
      - isotope-net
    ports:
      - "9003:9000"
      - "8083:8081"
    volumes:
      - ./state:/root/state
    environment:
      - NODE_ID=3
      - ISOTOPE_ETHICS_HASH=${ISOTOPE_ETHICS_HASH}

networks:
  isotope-net:
    driver: bridge