services:
  node1:
    build: ./node
    restart: unless-stopped
    networks:
      - isotope-net
    ports:
      - "9001:9000"
      - "8081:8081"
    volumes:
      - ./state:/root/state
    environment:
      - NODE_ID=1
      - ISOTOPE_STATE_PASSWORD=${ISOTOPE_STATE_PASSWORD:-}

  node2:
    build: ./node
    restart: unless-stopped
    networks:
      - isotope-net
    ports:
      - "9002:9000"
      - "8082:8081"
    volumes:
      - ./state:/root/state
    environment:
      - NODE_ID=2
      - ISOTOPE_STATE_PASSWORD=${ISOTOPE_STATE_PASSWORD:-}

  node3:
    build: ./node
    restart: unless-stopped
    networks:
      - isotope-net
    ports:
      - "9003:9000"
      - "8083:8081"
    volumes:
      - ./state:/root/state
    environment:
      - NODE_ID=3
      - ISOTOPE_STATE_PASSWORD=${ISOTOPE_STATE_PASSWORD:-}

  node4:
    build: ./node
    restart: unless-stopped
    networks:
      - isotope-net
    ports:
      - "9004:9000"
      - "8084:8081"
    volumes:
      - ./state:/root/state
    environment:
      - NODE_ID=4
      - ISOTOPE_STATE_PASSWORD=${ISOTOPE_STATE_PASSWORD:-}

  node5:
    build: ./node
    restart: unless-stopped
    networks:
      - isotope-net
    ports:
      - "9005:9000"
      - "8085:8081"
    volumes:
      - ./state:/root/state
    environment:
      - NODE_ID=5
      - ISOTOPE_STATE_PASSWORD=${ISOTOPE_STATE_PASSWORD:-}

networks:
  isotope-net:
    driver: bridge