name: iso_mobile
description: ISOTOPE — децентрализованная P2P-сеть для обмена сообщениями
publish_to: 'none'
version: 1.20.0+20

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  http: ^1.2.0
  web_socket_channel: ^2.4.5
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.4
  connectivity_plus: ^6.1.5
  permission_handler: ^11.4.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.2.3
  flutter_blue_plus: ^2.3.12
  multicast_dns: ^0.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true